### ISSUE TITLE
Bridging code introduces spurious space at document start

### ISSUE THREAD

**Issue by ghost** [loopspace/spath3#18]
Consider the preamble suggested by the manual of v2.4, page 20:
```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{intersections,spath3}
\tikzset{
  bridging path/.initial=arc,
  bridging span/.initial=8pt,
  bridging gap/.initial=4pt,
  bridge/.style 2 args={
    spath/split at intersections with={#1}{#2},
    spath/insert gaps after components={#1}{\pgfkeysvalueof{/tikz/bridging span}},
    spath/join components upright with={#1}{\pgfkeysvalueof{/tikz/bridging path}},
    spath/split at intersections with={#2}{#1},
    spath/insert gaps after components={#2}{\pgfkeysvalueof{/tikz/bridging gap}},
  }
}
% \AtBeginDocument{
%   \tikz[overlay] \path[spath/save=arc] (0,0) arc[radius=1cm, start angle=180, delta angle=-180];
% }
\begin{document}
First line
\end{document}

```
When uncommenting the three lines \AtBeginDocument{…}, we get spurious space at the start of the document. (This may seem small, but in a larger example involving svmono and tons of other packages – which I unfortunately cannot cite – this issue magnifies such that I even get one spurious page at the start of the document.) This is a bug and should not happen. Here is the screenshot of diffpdf (the compilation result for the commented version is on the left, for the uncommented version on the right):
![diffpdf_screenshot](https://user-images.githubusercontent.com/87096025/133865620-2befd201-acbf-4640-a4b8-7fb9d2fbe765.png)
I would be happy if this issue finds attention. Thanks in advance.

**Comment by kpym** [comment]
IMO, the problem comes from a space(s) introduced by the new line inside `\AtBeginDocument`. For me it is ok when I add comments at the end of the lines (which is a good practice) : 

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{intersections,spath3}
\tikzset{
  bridging path/.initial=arc,
  bridging span/.initial=8pt,
  bridging gap/.initial=4pt,
  bridge/.style 2 args={
    spath/split at intersections with={#1}{#2},
    spath/insert gaps after components={#1}{\pgfkeysvalueof{/tikz/bridging span}},
    spath/join components upright with={#1}{\pgfkeysvalueof{/tikz/bridging path}},
    spath/split at intersections with={#2}{#1},
    spath/insert gaps after components={#2}{\pgfkeysvalueof{/tikz/bridging gap}},
  }
}
\AtBeginDocument{%
  \tikz[overlay] \path[spath/save=arc] (0,0) arc[radius=1cm, start angle=180, delta angle=-180];%
}
\begin{document}
First line
\end{document}
```

**Comment by loopspace** [comment]
This is addressed at https://tex.stackexchange.com/q/605800/86 and two solutions are presented there.  I'll update the documentation to use those solutions rather than the current one.

**Comment by PeterMuellerr** [comment]
@kpym Thanks! Your solution (introducing %) works indeed for the minimal example at hand.
@loopspace Thanks! Please update the documentation the way you think it should be correct.

**Comment by PeterMuellerr** [comment]
@loopspace Any progress on the documentation (perhaps, with a bit of testing) so far?

**Comment by loopspace** [comment]
Must admit that this slipped my mind.  Thanks for the nudge.

**Comment by loopspace** [comment]
I've added a comment about this in the documentation, fix is https://github.com/loopspace/spath3/commit/8fcb4cb0a83b8a6c4930a6a7c0b2c4f08301a207, with a link to the TeX-SX question.
