### ISSUE TITLE
Can `every strand/.style` be added to `tikzpicture` environment?

### ISSUE THREAD

**Issue by Andrew15-5** [loopspace/spath3#25]
I want to modify example from https://github.com/loopspace/spath3/issues/22#issuecomment-1454947343 like this (just as a silly example):

```latex
\begin{tikzpicture}[
    arrow/.style={-Triangle},
    every strand/.style={only when rendering/.style={arrow}},
  ]
  \samecode
  \begin{knot}
    \strand (a.east) -- (b.west);
  \end{knot}
\end{tikzpicture}
```

But instead of 

![image](https://user-images.githubusercontent.com/37143421/222936388-92a78463-4770-495d-8ee0-b75e42e18cc5.png)

I get

![image](https://user-images.githubusercontent.com/37143421/222936370-6484e378-9ca3-444f-9bae-c58433aa98f9.png)

There are probably more valid examples of using `every strand/.style` but it is a useful "command", right? Can it be added?

**Comment by loopspace** [comment]
Page 10 of the knots documentation covers this. The knot keys are in their own directory, `knot diagram`, so if you want to define a key outside the knot environment then you need to use a prefix.

**Comment by Andrew15-5** [comment]
Right, thanks. But I have a following question. If this works:

```latex
\begin{tikzpicture}[
    arrow/.style={-Triangle},
    knot diagram/every knot diagram/.style={only when rendering/.style={arrow}},
  ]
  \samecode
  \begin{knot}[
      % every knot diagram/.style={only when rendering/.style={arrow}},
    ]
    \strand (a.east) -- (b.west);
  \end{knot}
\end{tikzpicture}
```

Then why this doesn't work:

```latex
\begin{tikzpicture}[
    arrow/.style={-Triangle},
    % knot diagram/every knot diagram/.style={only when rendering/.style={arrow}},
  ]
  \samecode
  \begin{knot}[
      every knot diagram/.style={only when rendering/.style={arrow}},
      % knot diagram/every knot diagram/.style={only when rendering/.style={arrow}}, % This also doesn't work
    ]
    \strand (a.east) -- (b.west);
  \end{knot}
\end{tikzpicture}
```

Do I read documentation incorrectly?

![image](https://user-images.githubusercontent.com/37143421/222991422-4f2e3b2e-442a-4ab3-bdc9-d05f447b5c62.png)

**Comment by loopspace** [comment]
The key `every knot diagram` is processed at the start of the knot environment, so setting it in the options on that environment is too late.

**Comment by Andrew15-5** [comment]
Am I right in understanding that there is no way to set `every knot diagram/.style` without adding the `knot diagram/` prefix? Because this prefix is only implied in the `knot` environment but setting `every knot diagram/.style` in it is too late.

**Comment by loopspace** [comment]
That is correct. I try to keep from polluting the main tikz namespace by putting my keys in families.
