### ISSUE TITLE
Incomplete key name `[at] end path construction` in doc

### ISSUE THREAD

**Issue by muzimuzhi** [loopspace/spath3#32]
In doc `spath3.pdf`, key `at end path construction` marked inside `{verbatim}` environment is typeset without the beginning `at`.
https://github.com/loopspace/spath3/blob/2b32ddeea7bc09a1579c7a500d1bc51f71cac3d6/spath3.tex#L144-L146
![image](https://github.com/user-attachments/assets/12a411b7-f39f-4dd4-96cf-370afa06d761)

It's a surprising gift from `l3doc`, as `l3doc` loads `fancyvrb` and [sets](https://github.com/latex3/latex3/blob/90bed66c868583929d582dc53c206486e9e8b5b7/l3kernel/l3doc.dtx#L1574-L1583)
```tex
\fvset{gobble=2}
\cs_gset_eq:NN \verbatim \Verbatim
\cs_gset_eq:NN \endverbatim \endVerbatim
```

`spath3.tex` can either indent all `{verbatim}` lines by 2 (extra) spaces or reset gobbling option by `\fvset{gobble=0}`.

**Comment by loopspace** [comment]
Thanks for spotting that. I've gone for the `\fvset{gobble=0}` fix as it seems more robust for my document.

Fixed in https://github.com/loopspace/spath3/commit/be3c27b39755be6074fcd238cb46ce74cd942284
