### ISSUE TITLE
space placed between consecutive characters when copy and paste code from manual.

### ISSUE THREAD

**Issue by AndreC75** [loopspace/spath3#5]
when you copy and paste the manual code, a space is always placed between two consecutive characters. Thus the command \strand becomes `\ s t r a n d. 
Could you modify the documentation to make it easier to copy and paste?

**Comment by kpym** [comment]
This is related to [this issue](https://github.com/loopspace/hobby/issues/3) I think.

**Comment by loopspace** [comment]
I believe so ...

**Comment by loopspace** [comment]
Fixed in https://github.com/loopspace/spath3/commit/fd54d284a2bc59a9830bbee106f5fa934dc3af1e (I hope!)
